A fun tool for painting things
zero01101/openOutpaint pull request #64
Opened 2022-12-01 22:08 UTC by seijihariki

A tool to use your master Microsoft Paint® artist skills to help you on your Stable Diffusion endeavors. 

Not much to say about it, really. Other than, the color picker of browsers doesn't seem to pick colors correctly with the stacked canvas system we are using, so we'll have to make our own.

Basically, the mask brush tool but for the image layer. When painting, it also (optionally) paints the equivalent mask (though I did not check if that works well with the blur):

https://user-images.githubusercontent.com/7552751/205165742-1b6fa777-4783-400a-ad76-fc4516e0a42d.mp4

Also works to give some better initial instructions

https://user-images.githubusercontent.com/7552751/205169129-72f2e792-8533-4e98-9a81-9ee5084ff636.mp4

Someone with a better drawing hand than I would probably do a much better job at this.

2022-12-01 23:44 UTC, zero01101 commented
i could kiss you

2022-12-02 01:49 UTC, zero01101 commented
>(though I did not check if that works well with the blur):

lol the auto-color-brush mask definitely gets eaten by overmask, terribly sorry about that :badpokerface:

2022-12-02 21:07 UTC, seijihariki commented
These last two commits add just actions (rename/delete) to resources, and updates the connection status indicator a bit

2022-12-02 22:25 UTC, zero01101 commented
hah, my last commit was to just ensure that `stored` isn't null if the json.parse has nothing in localstorage to parse :D  loving all of this so far

2022-12-02 22:26 UTC, zero01101 approved these changes
minus the unsolved mask brush being left behind if a color brush is "undone" instead of erased, this is all magnificent and too much fun

2022-12-02 23:53 UTC, seijihariki commented
> minus the unsolved mask brush being left behind if a color brush is "undone" instead of erased, this is all magnificent and too much fun

That was kind of deliberate, as we kinda stablished that the history does nothing to the mask with our 

> 
> [edit] is there any way to _unselect_ a style? might need a "none" option added back in

That's a good point! I did not have much time to test those features, as you can see by my very professional and clear commit titles.

It seems you have developed a fix! I'll give that a look as soon as I can.

2022-12-03 00:00 UTC, zero01101 commented
totally agreed re: "idempotency" of masks and _really_ solid point about mixed mask layer history 😬 i just foresee a potential user (read as: me) undoing a sketch and getting the mask results unexpectedly down the line lol, but that sounds like a job for docs more than anything ;) 

> as you can see by my very professional and clear commit titles.

lmao have you seen some of the garbage i emit

2022-12-03 05:51 UTC, seijihariki commented on js/index.js
> +	localStorage.setItem("promptStyle", JSON.stringify(selectedString));
Yeah, my naming conventions were not really clear... selectedString is actually an array of strings. This comparison may have worked due to automagic JavaScript casting, but I wouldn't bet on the consistency of that.

2022-12-03 05:55 UTC, seijihariki commented on js/index.js
> +	localStorage.setItem("promptStyle", JSON.stringify(selectedString));
This last commit now fixes this, but also clears all selections if "None" is ever selected, as well as adding a helpful check indicator on applied styles:
![image](https://user-images.githubusercontent.com/7552751/205426654-df3ecdb0-16e9-4a26-ac76-08b5168e4637.png)

None in action:

https://user-images.githubusercontent.com/7552751/205426710-71322f8e-b3f2-49b9-a96b-1522bf56869c.mp4

2022-12-03 13:22 UTC, seijihariki commented
This last one is quite interesting. I felt the mouse wheel was lonely on the dream() tools. So, I did something with it.

Adds dream reticle size separated from Stable Diffusion resolution. That makes it possible to manually do what full resolution inpainting does, and makes us able to better add smaller details to a scene. Also makes it possible to replicate auto TXT to image fix functionality.

Specific region inpainting:

https://user-images.githubusercontent.com/7552751/205442690-b90982ad-1366-49ef-8264-1937f9d28df0.mp4

Big image generation, then local upscaling:

https://user-images.githubusercontent.com/7552751/205442830-efa9cb46-9f74-488b-a623-8d7e50c03c16.mp4

But basically, this functionality gives us much more freedom to generate images and insert them into the world.

Obs: Please don't mind that it always generates women. For some reason, the Beautiful # styles I have always end up doing women unless I specify.

2022-12-03 16:01 UTC, zero01101 commented
decoupling the requested generation resolution from the resultant output resolution is super clever, my only complaint is that i'll have to rewrite some readme fundamentals ;)

2022-12-03 16:04 UTC, zero01101 requested changes
all systems go minus dream.js:432 and :434 :)

2022-12-03 16:09 UTC, seijihariki commented on js/ui/tool/dream.js
> +					downloadCanvas({canvas: auxCanvas, filename: null});
That's a good point!

2022-12-03 16:22 UTC, seijihariki commented
Will merge here then

2022-12-03 16:22 UTC, merged

2022-12-03 16:39 UTC, zero01101 commented
omg you even added error handling for failed dreams you are a hero